name: AntiCheatReloaded
author: Rammelkast
description: AntiCheatReloaded helps easily identify and block malicious users on your server.
main: com.rammelkast.anticheatreloaded.AntiCheatReloaded
api-version: 1.13
depend: [ProtocolLib]
startup: postworld
version: ${project.build.version}
commands:
  anticheatreloaded:
    description: Main AntiCheatReloaded command
    usage: /anticheatreloaded help
    aliases: acr
permissions: